### ISSUE TITLE
ensure_canary_pod uses self.api_version for ownerReference instead of owner's api_version

### ISSUE THREAD

**Issue by linkous8** [opsani/servox#97]
https://github.com/opsani/servox/blob/d95b76b0230ce384b9fab1df010dde5f6fbfe360/servo/connectors/kubernetes.py#L1401-L1408

Caught by @rstarmer , this produces a bit of a mismatch as seen below (name and uid redacted):

```
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: opsani-servo
    uid: xxxxxxx
```

I recommend the following fix: https://github.com/opsani/servox/blob/4357abb348c5a9d701107e2a327c9bcf771a731a/servo/connectors/kubernetes.py#L1309
